//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Student
    {
        public long Activity_Student_ID { get; set; }
        public string Student_ID { get; set; }
        public long Activity_ID { get; set; }
        public string Student_Name { get; set; }
        public string Attend { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Student Student { get; set; }
    }
}
