//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DassForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DassForm()
        {
            this.Question_DassForm = new HashSet<Question_DassForm>();
        }
    
        public long Form_ID { get; set; }
        public string Student_ID { get; set; }
        public string Condition { get; set; }
        public long Result_Stress { get; set; }
        public long Result_Anxiety { get; set; }
        public long Result_Depression { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_DassForm> Question_DassForm { get; set; }
    }
}
