//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PKPMentalHealthRecoveryEntities : DbContext
    {
        public PKPMentalHealthRecoveryEntities()
            : base("name=PKPMentalHealthRecoveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activity_Staff> Activity_Staff { get; set; }
        public virtual DbSet<Activity_Student> Activity_Student { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<DassForm> DassForms { get; set; }
        public virtual DbSet<LogBook> LogBooks { get; set; }
        public virtual DbSet<Meeting_Record> Meeting_Record { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Question_DassForm> Question_DassForm { get; set; }
        public virtual DbSet<Recommended_Activity> Recommended_Activity { get; set; }
    
        [DbFunction("PKPMentalHealthRecoveryEntities", "compareDateForchart")]
        public virtual IQueryable<compareDateForchart_Result> compareDateForchart(Nullable<System.DateTime> compareMonth)
        {
            var compareMonthParameter = compareMonth.HasValue ?
                new ObjectParameter("CompareMonth", compareMonth) :
                new ObjectParameter("CompareMonth", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<compareDateForchart_Result>("[PKPMentalHealthRecoveryEntities].[compareDateForchart](@CompareMonth)", compareMonthParameter);
        }
    
        [DbFunction("PKPMentalHealthRecoveryEntities", "Fun_EmployeeInformation")]
        public virtual IQueryable<Fun_EmployeeInformation_Result> Fun_EmployeeInformation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fun_EmployeeInformation_Result>("[PKPMentalHealthRecoveryEntities].[Fun_EmployeeInformation]()");
        }
    }
}
