//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_DassForm
    {
        public long QDS_ID { get; set; }
        public long Form_ID { get; set; }
        public string Student_ID { get; set; }
        public long Q1_Value { get; set; }
        public long Q2_Value { get; set; }
        public long Q3_Value { get; set; }
        public long Q4_Value { get; set; }
        public long Q5_Value { get; set; }
        public long Q6_Value { get; set; }
        public long Q7_Value { get; set; }
        public long Q8_Value { get; set; }
        public long Q9_Value { get; set; }
        public long Q10_Value { get; set; }
        public long Q11_Value { get; set; }
        public long Q12_Value { get; set; }
        public long Q13_Value { get; set; }
        public long Q14_Value { get; set; }
        public long Q15_Value { get; set; }
        public long Q16_Value { get; set; }
        public long Q17_Value { get; set; }
        public long Q18_Value { get; set; }
        public long Q19_Value { get; set; }
        public long Q20_Value { get; set; }
        public long Q21_Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual DassForm DassForm { get; set; }
        public virtual Student Student { get; set; }
    }
}
