//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommended_Activity
    {
        public long RA_ID { get; set; }
        public string Session_ID { get; set; }
        public long Activity_ID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Session Session { get; set; }
    }
}
