//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long Schedule_ID { get; set; }
        public string Student_ID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> Time_Start { get; set; }
        public Nullable<System.DateTime> Time_End { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
