//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHRS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Activity_Student = new HashSet<Activity_Student>();
            this.DassForms = new HashSet<DassForm>();
            this.Schedules = new HashSet<Schedule>();
            this.Sessions = new HashSet<Session>();
            this.Question_DassForm = new HashSet<Question_DassForm>();
        }

        [Required]
        [StringLength(10, ErrorMessage = "Student Id not be exceed")]
        [DisplayName("Student ID")]
        public string Student_ID { get; set; }
        [Required]
        [DisplayName("First Name")]
        public string Fname { get; set; }
        [Required]
        [DisplayName("Last Name")]
        public string Lname { get; set; }
        public string Faculty { get; set; }
        [Required]
        public string Course { get; set; }
        //[Required]
        public string Year { get; set; }
        //[Required]
        public string Semester { get; set; }
        //[Range(10, 11)]
        //[Required]
        [DisplayName("Phone No.")]
        public string Phone_No { get; set; }
        [Required]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Please enter valid email")]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        [DisplayName("Role")]
        public int Role_ID { get; set; }
        public byte[] Student_Image { get; set; }

        public string DisplayName
        {
            get
            {
                return this.Fname + " " + this.Lname.ToString();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Student> Activity_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DassForm> DassForms { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_DassForm> Question_DassForm { get; set; }
    }
}
